config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'

  get '/my_portfolio', to: 'users#my_portfolio'
  get '/search_stocks', to: 'stocks#search'
  resources :user_stocks, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  def self.find_by_ticker(ticker)
    where(ticker: ticker).first
  end

  def self.new_from_lookup(ticker)
    begin
      stock = StockQuote::Stock.quote(ticker)
      price = stock.l.gsub(',', '').to_d
      new(name: stock.name, ticker: stock.symbol, last_price: price)
    rescue Exception => e
      logger.debug e
      nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].blank?
      flash.now[:error] = 'Please enter a ticker to search'
    else
      @stock = Stock.new_from_lookup(params[:stock])
      flash.now[:error] = "\"#{params[:stock]}\" cannot be found" unless @stock
    end
    respond_to do |format|
      format.js { render partial: 'users/result' }
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.find_by_ticker(params[:stock])
    if !stock.present?
      stock = Stock.new_from_lookup(params[:stock])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "#{stock.ticker} added to your portfolio"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/views/layouts/_message.html.erb
<% if !flash[:notice].nil? %>
  <div class="alert alert-primary alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if !flash[:alert].nil? %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if !flash[:error].nil? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= flash[:error] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Finance Tracker', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Articles', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Users', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item dropdown">
        <a
          class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'All categories', root_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
      <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>FinanceTracker</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/message' %>
    <div class="container pt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_result.html.erb
<%= render 'layouts/message' %>
<% if @stock %>
  <div class="well">
    Name: <%= @stock.name %><br/>
    Symbol: <%= @stock.ticker %><br/>
    Last price: <%= @stock.last_price %><br/>
    <%= link_to 'Add to my portfolio',
      user_stocks_path(stock: @stock.ticker),
      class: 'btn btn-xs btn-success', method: :post %>
  </div>
<% end %>

app/views/users/_result.js.erb
$('#result').html("<%= j (render 'users/result.html') %>")

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<h3>Search for stock</h3>
<%= form_tag search_stocks_path, remote: true, method: :get do %>
  <div class="input-group mb-3">
    <%= text_field_tag :stock, params[:stock], autofocus: true,
      class: 'form-control',  'aria-describedby': 'basic-addon2' %>
    <div class="input-group-append">
      <%= button_tag type: :submit, class: 'btn btn-primary' do %>
        <i class="fa fa-search"></i>
        Search
      <% end %>
    </div>
  </div>
<% end %>

<div id="result">
  <%= render 'result' %>
</div>

app/views/welcome/index.html.erb
<h1>Hello</h1>
<%= link_to 'Log out', destroy_user_session_path, method: :delete %>